name: Windows CI

# Workflow for building BibleTime for Windows
#
# cmake is used to checkout, configure, and build
# the following projects
#     zlib, curl, clucene, sword, and bibletime

on:
  repository_dispatch:

env:
  BT_VERSION: 3.0.2
  QT_VERSION: 5.15.2

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-2019]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Install NSIS
      run: choco install nsis

    - name: Running cmake
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake .. 

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3


    - name: Build BibleTime Installer
      run: |
        cd build
        "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary/Build\vcvars64.bat"
        MSBuild.exe  /p:Configuration=Release /p:Platform=x64 bibletime-win.sln

    - name: Save BibleTime Installer
      uses: actions/upload-artifact@v2
      with:
        name: bibletime-x64-installer
        path: build\bibletime-prefix\src\bibletime-build\BibleTime-${{env.BT_VERSION}}-win64.exe
        retention-days: 5

    - name: Show Environment 
      run: |
        env
        Get-Location

