name: CI
# Workflow for building BibleTime for Windows
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-2019]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_msvc2019'
        dir: '${{ github.workspace }}/'



      #    - name: Running cmake (windows)
      #run: |
      #cd ${{ github.workspace }}
      #mkdir build
      #cd build
      #cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}
      #/../vcpkg/scripts/buildsystems/vcpkg.cmake
      #
      #- name: Build Solution (windows)
      #run: |
      #cd build
      #MSBuild.exe CMakeHelloWorld.sln
