name: CI
# Workflow for building BibleTime for Windows
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  Windows:
    name: build-windows
    runs-on: [windows-2019]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Install NSIS
      run: choco install nsis

    - name: Running cmake
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake .. 

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3


    - name: Build BibleTime Installer
      run: |
        cd build
        "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary/Build\vcvars64.bat"
        MSBuild.exe  /p:Configuration=Release bibletime-win.sln
